# Reference: https://docs.docker.com/compose/gettingstarted/
version: '3'
services:
#  web:
#    build: .
#    ports:
#      - "5000:5000"
#
#    depends_on:
#      - postgresdb
  postgresdb:
    image: "postgres"
    ports:
      - "5432:5432"